repos:
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16  # Use the ref you want to point at
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-deflist  # Not currently used AFAICT, but could be
    - mdformat-gfm
    - mdformat-frontmatter
    - mdformat-footnote
    - mdformat-tables   # Not currently used AFAICT, but could be
